# Generated by Django 3.2 on 2021-06-12 10:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cookie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('ip', models.GenericIPAddressField()),
                ('ora_data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Informatie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid', models.BooleanField(default=True)),
                ('target', models.CharField(max_length=100)),
                ('acuratete', models.SmallIntegerField()),
                ('informatii', models.TextField()),
                ('ora_data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('ora_data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Locatie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=13)),
                ('lon', models.CharField(max_length=13)),
                ('acc', models.FloatField(default=10000)),
                ('ora_data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Persoana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=50)),
                ('prenume', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=10, unique=True)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=50)),
                ('nume_display', models.CharField(max_length=50)),
                ('permisiune', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Supraveghetor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=50)),
                ('ora_data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('logid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('chat_room', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('data_inregistrare', models.DateTimeField(default=django.utils.timezone.now)),
                ('nume', models.CharField(max_length=50)),
                ('prenume', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefon', models.CharField(max_length=10, unique=True)),
                ('status', models.IntegerField(default=0)),
                ('cookies', models.ManyToManyField(blank=True, to='backend.Cookie')),
                ('ips', models.ManyToManyField(blank=True, to='backend.IP')),
                ('locatii', models.ManyToManyField(blank=True, to='backend.Locatie')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.rol')),
            ],
        ),
    ]
