# Generated by Django 3.2 on 2021-06-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='incredere',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='cookies',
            field=models.ManyToManyField(blank=True, null=True, to='backend.Cookie'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ips',
            field=models.ManyToManyField(blank=True, null=True, to='backend.IP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='locatii',
            field=models.ManyToManyField(blank=True, null=True, to='backend.Locatie'),
        ),
    ]
