# Generated by Django 3.2 on 2021-07-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210709_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookiemeta',
            name='dpi',
            field=models.SmallIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='cookiemeta',
            name='height',
            field=models.SmallIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='cookiemeta',
            name='width',
            field=models.SmallIntegerField(default=-1),
        ),
    ]
