# Generated by Django 3.2 on 2021-07-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20210727_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='id_aplica',
            field=models.SmallIntegerField(default=-1),
        ),
    ]
