# Generated by Django 3.2 on 2021-07-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_rol_id_aplica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geotrack',
            name='loc',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='geotrack',
            name='oras',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='geotrack',
            name='regiune',
            field=models.CharField(max_length=80),
        ),
    ]
