# Generated by Django 3.2 on 2021-08-06 18:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20210729_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indiciu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('text', models.TextField()),
                ('rasp', models.CharField(max_length=300)),
                ('poza', models.ImageField(upload_to='')),
                ('dificultate', models.SmallIntegerField()),
                ('persoane_simultan', models.SmallIntegerField(default=2)),
                ('locatie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.locatie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='cid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='IndiciuMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ora_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('indiciu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.indiciu')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Echipa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('nume', models.CharField(max_length=150)),
                ('telefon', models.CharField(max_length=10, unique=True)),
                ('persoane', models.SmallIntegerField()),
                ('dificultate', models.SmallIntegerField()),
                ('indicii', models.ManyToManyField(blank=True, to='backend.IndiciuMeta')),
                ('locatii', models.ManyToManyField(blank=True, to='backend.Locatie')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
