# Generated by Django 3.2 on 2021-08-06 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20210806_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='echipa',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='indiciu',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='indiciumeta',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cid',
        ),
    ]
