# Generated by Django 3.2 on 2021-08-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20210806_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nick',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='cookies',
            field=models.ManyToManyField(blank=True, to='backend.Cookie'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ips',
            field=models.ManyToManyField(blank=True, to='backend.IP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='locatii',
            field=models.ManyToManyField(blank=True, to='backend.Locatie'),
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liber', models.BooleanField(default=True)),
                ('persoane', models.ManyToManyField(blank=True, to='backend.User')),
            ],
        ),
    ]
