# Generated by Django 3.2 on 2021-08-08 12:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20210808_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='prenume',
        ),
        migrations.AddField(
            model_name='user',
            name='data_nastere',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='nume',
            field=models.CharField(max_length=150),
        ),
    ]
