# Generated by Django 3.2 on 2021-08-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20210808_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activitate',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='rookie',
            field=models.BooleanField(default=True),
        ),
    ]
