# Generated by Django 3.2 on 2021-08-11 15:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20210811_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookie',
            name='metadate',
            field=models.ManyToManyField(blank=True, to='backend.CookieMeta'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=400)),
                ('desc', models.TextField()),
                ('maxim_membri', models.SmallIntegerField(default=10)),
                ('participanti', models.ManyToManyField(blank=True, to='backend.User')),
            ],
        ),
        migrations.CreateModel(
            name='Sedinta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=400)),
                ('desc', models.TextField()),
                ('data_ora', models.DateTimeField(default=django.utils.timezone.now)),
                ('durata', models.SmallIntegerField(default=2)),
                ('maxim_membri', models.SmallIntegerField(default=10)),
                ('participanti', models.ManyToManyField(blank=True, related_name='sedinta_participanti', to='backend.User')),
                ('prezenti', models.ManyToManyField(blank=True, related_name='sedinta_prezenti', to='backend.User')),
            ],
        ),
    ]
