# Generated by Django 3.2 on 2021-08-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20210811_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='indiciumeta',
            name='rezolvat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='indiciumeta',
            name='sarit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='nick',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
