# Generated by Django 3.2 on 2021-08-24 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20210813_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liber', models.BooleanField(default=True)),
                ('locatie', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='backend.locatie')),
            ],
        ),
        migrations.RenameField(
            model_name='indiciu',
            old_name='persoane_simultan',
            new_name='echipe_simultan',
        ),
        migrations.AlterField(
            model_name='sedinta',
            name='participanti',
            field=models.ManyToManyField(blank=True, related_name='participanti', to='backend.User'),
        ),
        migrations.AlterField(
            model_name='sedinta',
            name='prezenti',
            field=models.ManyToManyField(blank=True, related_name='prezenti', to='backend.User'),
        ),
        migrations.DeleteModel(
            name='Station',
        ),
    ]
