# Generated by Django 3.2 on 2021-08-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20210824_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='indiciu',
            name='adugat_de',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='locatie',
            name='viteza',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='locatie',
            name='lat',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='locatie',
            name='lon',
            field=models.CharField(max_length=15),
        ),
    ]
