# Generated by Django 3.2 on 2021-08-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20210825_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indiciu',
            name='poza',
            field=models.ImageField(upload_to='incarcari/th/%Y%m%d%H%M%S%s'),
        ),
    ]
