# Generated by Django 3.2 on 2021-08-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_auto_20210826_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='indiciu',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
    ]
