# Generated by Django 3.2 on 2021-08-26 21:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_auto_20210826_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='punct',
            name='sid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
