# Generated by Django 3.2 on 2021-08-28 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_punct_ocupat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='echipa',
            name='nume',
        ),
    ]
