# Generated by Django 3.2 on 2021-08-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_remove_echipa_nume'),
    ]

    operations = [
        migrations.AddField(
            model_name='echipa',
            name='nume',
            field=models.CharField(default='', max_length=500),
        ),
    ]
