# Generated by Django 3.2 on 2021-08-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_echipa_nume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=200)),
                ('poza', models.ImageField(upload_to='incarcari/sponsori/%Y%m%d%H%M%S%s')),
                ('text', models.TextField()),
                ('link', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='echipa',
            name='greenGym',
            field=models.BooleanField(default=True),
        ),
    ]
