# Generated by Django 3.2 on 2021-09-04 07:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_auto_20210828_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rezervare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('nume', models.CharField(default='', max_length=300)),
                ('telefon', models.CharField(max_length=10, unique=True)),
                ('persoane', models.SmallIntegerField()),
                ('ip', models.GenericIPAddressField()),
            ],
        ),
    ]
