# Generated by Django 3.2 on 2021-09-04 21:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_rezervare'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cerinta', models.TextField()),
                ('poza', models.ImageField(upload_to='incarcari/taskuri/%Y%m%d%H%M%S%s')),
                ('timp', models.SmallIntegerField(default=5)),
            ],
        ),
        migrations.AddField(
            model_name='indiciu',
            name='echipe',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TaskMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ora_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('poza', models.ImageField(upload_to='incarcari/taskuri_echipe/%Y%m%d%H%M%S%s')),
                ('rezolvat', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.task')),
            ],
        ),
        migrations.AddField(
            model_name='echipa',
            name='taskuri',
            field=models.ManyToManyField(blank=True, to='backend.TaskMeta'),
        ),
    ]
