# Generated by Django 3.2 on 2021-09-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_auto_20210905_0050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='timp',
            new_name='timp_minute',
        ),
        migrations.RemoveField(
            model_name='punct',
            name='echipa',
        ),
        migrations.AddField(
            model_name='punct',
            name='echipe',
            field=models.ManyToManyField(blank=True, related_name='echipe', to='backend.Echipa'),
        ),
        migrations.AddField(
            model_name='punct',
            name='useri',
            field=models.ManyToManyField(blank=True, related_name='useri', to='backend.User'),
        ),
    ]
