# Generated by Django 3.2 on 2021-09-06 19:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_task_dificultate'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ora',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
