# Generated by Django 3.2 on 2021-09-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_task_ora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='punct',
            name='ocupat',
        ),
        migrations.AddField(
            model_name='taskmeta',
            name='trimis_la_analiza',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='taskmeta',
            name='poza',
            field=models.ImageField(blank=True, upload_to='incarcari/taskuri_echipe/%Y%m%d%H%M%S%s'),
        ),
    ]
