# Generated by Django 3.2 on 2021-09-06 20:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_remove_rezervare_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmeta',
            name='analizat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='treasurehuntsettings',
            name='greu_1',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='greu_1', to='backend.echipa'),
        ),
        migrations.AlterField(
            model_name='treasurehuntsettings',
            name='greu_2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='greu_2', to='backend.echipa'),
        ),
        migrations.AlterField(
            model_name='treasurehuntsettings',
            name='greu_3',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='greu_3', to='backend.echipa'),
        ),
        migrations.AlterField(
            model_name='treasurehuntsettings',
            name='greu_mentiune_1',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='greu_mentiune_1', to='backend.echipa'),
        ),
        migrations.AlterField(
            model_name='treasurehuntsettings',
            name='greu_mentiune_2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='greu_mentiune_2', to='backend.echipa'),
        ),
        migrations.AlterField(
            model_name='treasurehuntsettings',
            name='mediu_1',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mediu_1', to='backend.echipa'),
        ),
        migrations.AlterField(
            model_name='treasurehuntsettings',
            name='mediu_2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mediu_2', to='backend.echipa'),
        ),
        migrations.AlterField(
            model_name='treasurehuntsettings',
            name='mediu_3',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mediu_3', to='backend.echipa'),
        ),
        migrations.AlterField(
            model_name='treasurehuntsettings',
            name='mediu_mentiune_1',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mediu_mentiune_1', to='backend.echipa'),
        ),
        migrations.AlterField(
            model_name='treasurehuntsettings',
            name='mediu_mentiune_2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mediu_mentiune_2', to='backend.echipa'),
        ),
        migrations.AlterField(
            model_name='treasurehuntsettings',
            name='ora_incepere',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='treasurehuntsettings',
            name='ora_terminare',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='treasurehuntsettings',
            name='tombola',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tombola', to='backend.echipa'),
        ),
    ]
