# Generated by Django 3.2 on 2021-09-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_auto_20210906_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='echipa',
            name='baterie',
            field=models.SmallIntegerField(default=0),
        ),
    ]
