# Generated by Django 3.2 on 2021-09-06 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_echipa_baterie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasurehuntsettings',
            name='greu_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='greu_1', to='backend.echipa'),
        ),
        migrations.AlterField(
            model_name='treasurehuntsettings',
            name='greu_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='greu_2', to='backend.echipa'),
        ),
        migrations.AlterField(
            model_name='treasurehuntsettings',
            name='greu_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='greu_3', to='backend.echipa'),
        ),
        migrations.AlterField(
            model_name='treasurehuntsettings',
            name='greu_mentiune_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='greu_mentiune_1', to='backend.echipa'),
        ),
        migrations.AlterField(
            model_name='treasurehuntsettings',
            name='greu_mentiune_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='greu_mentiune_2', to='backend.echipa'),
        ),
        migrations.AlterField(
            model_name='treasurehuntsettings',
            name='mediu_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mediu_1', to='backend.echipa'),
        ),
        migrations.AlterField(
            model_name='treasurehuntsettings',
            name='mediu_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mediu_2', to='backend.echipa'),
        ),
        migrations.AlterField(
            model_name='treasurehuntsettings',
            name='mediu_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mediu_3', to='backend.echipa'),
        ),
        migrations.AlterField(
            model_name='treasurehuntsettings',
            name='mediu_mentiune_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mediu_mentiune_1', to='backend.echipa'),
        ),
        migrations.AlterField(
            model_name='treasurehuntsettings',
            name='mediu_mentiune_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mediu_mentiune_2', to='backend.echipa'),
        ),
        migrations.AlterField(
            model_name='treasurehuntsettings',
            name='tombola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tombola', to='backend.echipa'),
        ),
    ]
