# Generated by Django 3.2 on 2021-09-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0039_auto_20210907_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='indiciu',
            name='extremitate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='indiciu',
            name='green',
            field=models.BooleanField(default=False),
        ),
    ]
