# Generated by Django 3.2 on 2021-09-08 20:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0040_auto_20210908_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='indiciu',
            name='sid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
