# Generated by Django 3.2 on 2021-09-08 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0041_indiciu_sid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indiciu',
            old_name='sid',
            new_name='i_nume',
        ),
    ]
