# Generated by Django 3.2 on 2021-09-08 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0045_rename_sid_indiciu_i_sid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indiciu',
            name='i_sid',
        ),
    ]
