# Generated by Django 3.2 on 2021-09-08 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0046_remove_indiciu_i_sid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='echipa',
            old_name='sid',
            new_name='e_sid',
        ),
        migrations.RenameField(
            model_name='punct',
            old_name='sid',
            new_name='p_sid',
        ),
    ]
