# Generated by Django 3.2 on 2021-09-08 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0047_auto_20210908_2352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='echipa',
            old_name='e_sid',
            new_name='sid',
        ),
        migrations.RenameField(
            model_name='punct',
            old_name='p_sid',
            new_name='sid',
        ),
    ]
