# Generated by Django 3.2 on 2021-09-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0049_auto_20210909_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='echipa',
            name='platite',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='punct',
            name='au_fost',
            field=models.ManyToManyField(blank=True, related_name='au_fost', to='backend.Echipa'),
        ),
    ]
