# Generated by Django 3.2 on 2021-09-09 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0051_auto_20210909_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cookie',
            old_name='sid',
            new_name='c_sid',
        ),
        migrations.RenameField(
            model_name='grup',
            old_name='sid',
            new_name='g_sid',
        ),
        migrations.RenameField(
            model_name='statie',
            old_name='sid',
            new_name='st_sid',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='sid',
            new_name='u_sid',
        ),
    ]
