# Generated by Django 3.2 on 2021-09-09 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0052_auto_20210909_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cookie',
            old_name='c_sid',
            new_name='sid',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='u_sid',
            new_name='sid',
        ),
    ]
