# Generated by Django 3.2 on 2021-09-09 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0053_auto_20210909_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cookies',
        ),
        migrations.DeleteModel(
            name='Cookie',
        ),
    ]
