# Generated by Django 3.2 on 2021-09-09 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0054_auto_20210909_1256'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CookieMeta',
        ),
    ]
