# Generated by Django 3.2 on 2021-09-09 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0057_auto_20210909_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statie',
            name='echipe',
        ),
    ]
