# Generated by Django 3.2 on 2021-09-09 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0058_remove_statie_au_fost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statie',
            name='au_fost',
        ),
    ]
