# Generated by Django 3.2 on 2021-09-09 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0059_remove_statie_au_fost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Statie',
        ),
    ]
