# Generated by Django 3.2 on 2021-09-09 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0061_statie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Statie',
        ),
    ]
