# Generated by Django 3.2 on 2021-09-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0065_auto_20210909_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupTH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(default='', max_length=500)),
                ('telefon', models.CharField(max_length=10, unique=True)),
                ('persoane', models.SmallIntegerField()),
                ('dificultate', models.SmallIntegerField()),
                ('greenGym', models.BooleanField(default=True)),
                ('platite', models.SmallIntegerField(default=0)),
                ('baterie', models.SmallIntegerField(default=0)),
                ('incercari', models.TextField(blank=True, default='')),
                ('indicii', models.ManyToManyField(blank=True, to='backend.IndiciuMeta')),
                ('locatii', models.ManyToManyField(blank=True, to='backend.Locatie')),
                ('taskuri', models.ManyToManyField(blank=True, to='backend.TaskMeta')),
            ],
        ),
    ]
