# Generated by Django 3.2 on 2021-09-09 11:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0068_auto_20210909_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupth',
            name='sid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
