# Generated by Django 3.2 on 2021-09-09 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0069_grupth_sid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treasurehuntsettings',
            name='inceput',
        ),
        migrations.RemoveField(
            model_name='treasurehuntsettings',
            name='terminat',
        ),
    ]
