# Generated by Django 3.2 on 2021-09-09 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0073_auto_20210909_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupth',
            name='locatii',
        ),
        migrations.RemoveField(
            model_name='grupth',
            name='taskuri',
        ),
        migrations.AddField(
            model_name='grupth',
            name='conditii',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grupth',
            name='locatie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.locatie'),
        ),
        migrations.AddField(
            model_name='grupth',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.taskmeta'),
        ),
        migrations.AddField(
            model_name='task',
            name='trimis',
            field=models.BooleanField(default=False),
        ),
    ]
