# Generated by Django 3.2 on 2021-09-10 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0074_auto_20210909_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupth',
            name='baterie',
        ),
    ]
