# Generated by Django 3.2 on 2021-09-11 13:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0075_remove_grupth_baterie'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupth',
            name='fostStatie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grupth',
            name='inStatie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grupth',
            name='lastStatie',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='statie',
            name='locatie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.locatie'),
        ),
    ]
