# Generated by Django 3.2 on 2021-09-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0076_auto_20210911_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='indiciu',
            name='centru',
            field=models.BooleanField(default=False),
        ),
    ]
