# Generated by Django 3.2 on 2021-10-25 14:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0079_auto_20210911_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puncte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puncte', models.IntegerField(default=0)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Membruv2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('nume', models.CharField(max_length=150)),
                ('clasa', models.CharField(blank=True, default='', max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('telefon', models.CharField(max_length=10, unique=True)),
                ('data_nastere', models.DateTimeField(default=django.utils.timezone.now)),
                ('puncte', models.ManyToManyField(blank=True, to='backend.Puncte')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Intalnire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=400)),
                ('desc', models.TextField()),
                ('data_ora', models.DateTimeField(default=django.utils.timezone.now)),
                ('durata', models.SmallIntegerField(default=2)),
                ('participanti', models.ManyToManyField(blank=True, related_name='participantiv2', to='backend.Membruv2')),
            ],
        ),
    ]
