# Generated by Django 3.2 on 2021-10-31 13:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0080_intalnire_membruv2_puncte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Melodie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=400)),
                ('data_ora', models.DateTimeField(default=django.utils.timezone.now)),
                ('fisier', models.FileField(upload_to='frontend/productie/media/melodii/')),
                ('curenta', models.BooleanField(default=False)),
                ('pozitie', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
