# Generated by Django 3.2 on 2021-11-18 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0081_melodie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obiecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabla', models.BooleanField(default=False)),
                ('casa', models.BooleanField(default=False)),
                ('piatra', models.BooleanField(default=False)),
                ('moisil', models.BooleanField(default=False)),
                ('carte', models.BooleanField(default=False)),
                ('start1', models.DateTimeField(default=datetime.datetime)),
                ('start2', models.DateTimeField(default=datetime.datetime)),
                ('start3', models.DateTimeField(default=datetime.datetime)),
            ],
        ),
    ]
